const initialState = {
  answeredQuestions: [
    { answerID: '1', answer: '1' },
    { answerID: '2', answer: '1' },
    { answerID: '3', answer: '1' },
    { answerID: '4', answer: '1' },
    { answerID: '5', answer: '1' },
    { answerID: '6', answer: '1' },
    { answerID: '7', answer: '1' },
    { answerID: '8', answer: '1' },
    { answerID: '9', answer: '1' },
    { answerID: '10', answer: '1' },
  ],
  propositions: [
    {
      id: 1,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 2,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 3,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 4,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 5,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 6,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 7,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 8,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 9,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
    {
      id: 10,
      propositionAuthor: 'Brandon Santiago',
      propositionDescription: 'Sit libero fugit inventore quod nobis ipsum. Soluta sapiente molestiae id maxime.↵Quis asperiores maiores tempore.',
      propositionLink: 'https: //nunez-miranda.com/',
      propositionSubTitle: 'Maryland',
      propositionTitle: 'Angelachester',
    },
  ],
  actualQuestionID: 0,
};

export default initialState;
